#! /usr/bin/python

from twilio.rest import TwilioRestClient
import bitly_api
import datetime
import pickle
import random
import sys


messages = [", please fill out your link here: ", ", let us know how you're feeling here: "]

#load config files
config = {}
bitconfig = {}
execfile("twilio.conf", config)
execfile("bitly.conf", bitconfig)
client = TwilioRestClient(config["sid"], config["token"])

print "\n\n>>>>>>>>>>> textusers run at " + str(datetime.datetime.now()) + "\n\n"


#load users
try:
    users = pickle.load( open( "participants.p", "rb" ) )
except (OSError, IOError) as e:
    print e
    print "Warning: no participant file found.  exiting..."
    sys.exit()


#send text with twilio
for user in users:
    sendmessage = user['fname'] + random.choice(messages) + user['url']
    phonenum = "+1" + user['phone']
    print '---- sending to ' + str(user['fname']) + str(user['lname']) + ' ----'
    try:
        message = client.messages.create(to=phonenum, from_=config["phonenum"], body=sendmessage)
        print sendmessage
        print message
    except Exception as e:
        print e


#update bitly click statistics
print "checking/updating bit.ly links..."

c = bitly_api.Connection(access_token=bitconfig['token'])
for user in users:
    try:
        numclicks = c.clicks(shortUrl=user['url'])[0]['global_clicks']
        clickstoday = c.clicks_by_day(shortUrl=user['url'])[0]['clicks'][0]['clicks']
        print user['fname'] + " " + user['lname'] + ' total clicks=' + \
            str(numclicks) + " today=" + str(clickstoday)
        user["total_clicks"] = numclicks
        user["clicks_today"] = clickstoday
    except:
        print "ERROR: Couldn't read bitly link " + user['url'] + " for " + user['fname'] + " " + user['lname']
        user["total_clicks"] = None
        user["clicks_today"] = None

print "done."

#update day in program
print "updating days..."
for user in users:
    user['day'] = user['day'] + 1
print "done."

#save file after modifications
try:
    pickle.dump(users, open( "participants.p", "wb" ) )
    print 'user file saved.'
except (OSError, IOError) as e:
    print "Error: could not write to file. Try again..."
    print e

